/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Vinicius Ferreira
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        
        cadastrarFrameMenu.setVisible(false);
        DeletarFrameMenu.setVisible(false);
        FrameAtualizar.setVisible(false);
        ConsultarFrame.setVisible(false);
        ConsultarTodosFrame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarFrameMenu = new javax.swing.JInternalFrame();
        txtnome = new javax.swing.JTextField();
        txtcategoria = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cadastrarBtn = new javax.swing.JButton();
        platLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtlancamento = new javax.swing.JTextField();
        txtvenda = new javax.swing.JTextField();
        txtplataforma = new javax.swing.JTextField();
        platLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsinopse = new javax.swing.JTextField();
        txtnota = new javax.swing.JTextField();
        txtdev = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sucessoLbl = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        DeletarFrameMenu = new javax.swing.JInternalFrame();
        deletarBtn = new javax.swing.JButton();
        txtIdDeletar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cancelarDlt = new javax.swing.JButton();
        deletadolbl = new javax.swing.JLabel();
        FrameAtualizar = new javax.swing.JInternalFrame();
        AtualizarBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtplataformaupdate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtprecoupdate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtnotaupdate = new javax.swing.JTextField();
        lblAtualizado = new javax.swing.JLabel();
        cancelarUpdateBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtidupdate = new javax.swing.JTextField();
        ConsultarFrame = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultarList = new javax.swing.JList<>();
        ConsultarIdButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtidConsultarId = new javax.swing.JTextField();
        cancelarConsultarId = new javax.swing.JButton();
        LabelErro = new javax.swing.JLabel();
        ConsultarTodosFrame = new javax.swing.JInternalFrame();
        ConsultarTdsBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsultarTodos = new javax.swing.JList<>();
        CancelarTdsBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        arquivoMenu = new javax.swing.JMenu();
        cadastrarMenuItem = new javax.swing.JMenuItem();
        menuItemDeletar = new javax.swing.JMenuItem();
        menuItemAtualizar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuById = new javax.swing.JMenuItem();
        MenuTds = new javax.swing.JMenuItem();
        sobreMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(737, 601));

        cadastrarFrameMenu.setVisible(true);

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Categoria:");

        jLabel3.setText("Preco:");

        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        platLabel.setText("Plataformas:");

        jLabel5.setText("Quantidades Vendidas:");

        jLabel6.setText("Data de lançamento:");

        txtplataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplataformaActionPerformed(evt);
            }
        });

        platLabel1.setText("Desenvolvedora:");

        jLabel7.setText("Nota no MetaCritic:");

        jLabel8.setText("Sinopse:");

        txtsinopse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsinopseActionPerformed(evt);
            }
        });

        txtdev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdevActionPerformed(evt);
            }
        });

        sucessoLbl.setText("          ");

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastrarFrameMenuLayout = new javax.swing.GroupLayout(cadastrarFrameMenu.getContentPane());
        cadastrarFrameMenu.getContentPane().setLayout(cadastrarFrameMenuLayout);
        cadastrarFrameMenuLayout.setHorizontalGroup(
            cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarFrameMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(cadastrarFrameMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarFrameMenuLayout.createSequentialGroup()
                        .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrarFrameMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(platLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarFrameMenuLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtlancamento)
                            .addComponent(txtvenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtplataforma, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcategoria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpreco)
                            .addComponent(txtnota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarFrameMenuLayout.createSequentialGroup()
                            .addComponent(platLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtdev, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarFrameMenuLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtsinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarFrameMenuLayout.createSequentialGroup()
                            .addComponent(sucessoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancelarButton)
                            .addGap(18, 18, 18)
                            .addComponent(cadastrarBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadastrarFrameMenuLayout.setVerticalGroup(
            cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarFrameMenuLayout.createSequentialGroup()
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtplataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(platLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(platLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sucessoLbl)
                    .addGroup(cadastrarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadastrarBtn)
                        .addComponent(cancelarButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );

        DeletarFrameMenu.setVisible(true);

        deletarBtn.setText("Deletar");
        deletarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBtnActionPerformed(evt);
            }
        });

        txtIdDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDeletarActionPerformed(evt);
            }
        });

        jLabel9.setText("ID:");

        cancelarDlt.setText("Cancelar");
        cancelarDlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarDltActionPerformed(evt);
            }
        });

        deletadolbl.setText("     ");

        javax.swing.GroupLayout DeletarFrameMenuLayout = new javax.swing.GroupLayout(DeletarFrameMenu.getContentPane());
        DeletarFrameMenu.getContentPane().setLayout(DeletarFrameMenuLayout);
        DeletarFrameMenuLayout.setHorizontalGroup(
            DeletarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeletarFrameMenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeletarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DeletarFrameMenuLayout.createSequentialGroup()
                        .addComponent(deletarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletadolbl, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DeletarFrameMenuLayout.createSequentialGroup()
                        .addGroup(DeletarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelarDlt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdDeletar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DeletarFrameMenuLayout.setVerticalGroup(
            DeletarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletarFrameMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(DeletarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeletarFrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletarBtn)
                    .addComponent(deletadolbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelarDlt)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        FrameAtualizar.setBackground(new java.awt.Color(0, 0, 0));
        FrameAtualizar.setBorder(null);
        FrameAtualizar.setClosable(true);
        FrameAtualizar.setTitle("Atualizar");
        FrameAtualizar.setVisible(true);

        AtualizarBtn.setText("Atualizar");
        AtualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Plataforma: ");

        jLabel11.setText("Preço: ");

        jLabel12.setText("Nota MetaCritic:");

        lblAtualizado.setText("               ");

        cancelarUpdateBtn.setText("Cancelar");
        cancelarUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarUpdateBtnActionPerformed(evt);
            }
        });

        jLabel13.setText("Id:");

        javax.swing.GroupLayout FrameAtualizarLayout = new javax.swing.GroupLayout(FrameAtualizar.getContentPane());
        FrameAtualizar.getContentPane().setLayout(FrameAtualizarLayout);
        FrameAtualizarLayout.setHorizontalGroup(
            FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAtualizarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addGroup(FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cancelarUpdateBtn)
                        .addComponent(AtualizarBtn))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAtualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtidupdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(txtplataformaupdate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtprecoupdate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtnotaupdate, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        FrameAtualizarLayout.setVerticalGroup(
            FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameAtualizarLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(txtidupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txtplataformaupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecoupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtnotaupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtualizarBtn)
                    .addComponent(lblAtualizado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarUpdateBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConsultarFrame.setVisible(true);

        jScrollPane1.setViewportView(consultarList);

        ConsultarIdButton.setText("Consultar");
        ConsultarIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarIdButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Id:");

        txtidConsultarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidConsultarIdActionPerformed(evt);
            }
        });

        cancelarConsultarId.setText("Cancelar");
        cancelarConsultarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarConsultarIdActionPerformed(evt);
            }
        });

        LabelErro.setText("                                                                                      ");

        javax.swing.GroupLayout ConsultarFrameLayout = new javax.swing.GroupLayout(ConsultarFrame.getContentPane());
        ConsultarFrame.getContentPane().setLayout(ConsultarFrameLayout);
        ConsultarFrameLayout.setHorizontalGroup(
            ConsultarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ConsultarFrameLayout.createSequentialGroup()
                        .addGroup(ConsultarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConsultarFrameLayout.createSequentialGroup()
                                .addComponent(ConsultarIdButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelarConsultarId))
                            .addGroup(ConsultarFrameLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtidConsultarId, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelErro, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ConsultarFrameLayout.setVerticalGroup(
            ConsultarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultarFrameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ConsultarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtidConsultarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultarIdButton)
                    .addComponent(cancelarConsultarId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        ConsultarTodosFrame.setBackground(new java.awt.Color(255, 51, 255));
        ConsultarTodosFrame.setVisible(true);

        ConsultarTdsBtn.setText("Consultar Todos");
        ConsultarTdsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarTdsBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(ConsultarTodos);

        CancelarTdsBtn.setText("Cancelar");
        CancelarTdsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarTdsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultarTodosFrameLayout = new javax.swing.GroupLayout(ConsultarTodosFrame.getContentPane());
        ConsultarTodosFrame.getContentPane().setLayout(ConsultarTodosFrameLayout);
        ConsultarTodosFrameLayout.setHorizontalGroup(
            ConsultarTodosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarTodosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultarTodosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultarTodosFrameLayout.createSequentialGroup()
                        .addComponent(ConsultarTdsBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(ConsultarTodosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultarTodosFrameLayout.createSequentialGroup()
                    .addContainerGap(133, Short.MAX_VALUE)
                    .addComponent(CancelarTdsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(260, Short.MAX_VALUE)))
        );
        ConsultarTodosFrameLayout.setVerticalGroup(
            ConsultarTodosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarTodosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConsultarTdsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(ConsultarTodosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ConsultarTodosFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CancelarTdsBtn)
                    .addContainerGap(385, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinicius Ferreira\\Downloads\\8978277.jpg")); // NOI18N
        jLabel16.setText("jLabel16");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        arquivoMenu.setText("Arquivo");

        cadastrarMenuItem.setText("Cadastrar");
        cadastrarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMenuItemActionPerformed(evt);
            }
        });
        arquivoMenu.add(cadastrarMenuItem);

        menuItemDeletar.setText("Deletar");
        menuItemDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDeletarActionPerformed(evt);
            }
        });
        arquivoMenu.add(menuItemDeletar);

        menuItemAtualizar.setText("Atualizar");
        menuItemAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAtualizarActionPerformed(evt);
            }
        });
        arquivoMenu.add(menuItemAtualizar);

        jMenuBar1.add(arquivoMenu);

        jMenu2.setText("Consultar");

        menuById.setText("Por Id");
        menuById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuByIdActionPerformed(evt);
            }
        });
        jMenu2.add(menuById);

        MenuTds.setText("Todos");
        MenuTds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTdsActionPerformed(evt);
            }
        });
        jMenu2.add(MenuTds);

        jMenuBar1.add(jMenu2);

        sobreMenu.setText("Sobre");
        jMenuBar1.add(sobreMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1047, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(cadastrarFrameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(361, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(DeletarFrameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(402, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(201, 201, 201)
                    .addComponent(FrameAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(384, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(160, 160, 160)
                    .addComponent(ConsultarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(342, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ConsultarTodosFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(433, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(cadastrarFrameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(222, 222, 222)
                    .addComponent(DeletarFrameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(FrameAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(209, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(ConsultarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(ConsultarTodosFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(135, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuByIdActionPerformed
        // TODO add your handling code here:
        ConsultarFrame.setVisible(true);
    }//GEN-LAST:event_menuByIdActionPerformed

    private void menuItemDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDeletarActionPerformed
        // TODO add your handling code here:
        DeletarFrameMenu.setVisible(true);
    }//GEN-LAST:event_menuItemDeletarActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtdevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdevActionPerformed

    private void txtsinopseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsinopseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsinopseActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        // TODO add your handling code here:
        model.Games g = new model.Games();
        model.dao.GamesDAO gdao = new model.dao.GamesDAO();
        g.setNome(txtnome.getText());
        g.setSinopse(txtsinopse.getText());
        g.setDatalancamento(txtlancamento.getText());
        g.setPreco(Double.parseDouble(txtpreco.getText()));
        g.setPlataforma(txtplataforma.getText());
        g.setQuantidadesvendidas(Double.parseDouble(txtvenda.getText()));
        g.setCategoria(txtcategoria.getText());
        g.setDesenvolvedora(txtdev.getText());
        g.setNotametacritic(Double.parseDouble(txtnota.getText()));   
        try{
            gdao.cadastrar(g);
        }catch(SQLException | ClassNotFoundException ex){
            System.out.println("Erro...: " + ex.getMessage());
        }
        txtnome.setText("");
        txtsinopse.setText("");
        txtlancamento.setText("");
        txtpreco.setText("");
        txtplataforma.setText("");
        txtvenda.setText("");
        txtcategoria.setText("");
        txtdev.setText("");
        txtnota.setText("");
        sucessoLbl.setText("Cadastrado com Sucesso");
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void cadastrarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMenuItemActionPerformed
        // TODO add your handling code here:
        cadastrarFrameMenu.setVisible(true);
    }//GEN-LAST:event_cadastrarMenuItemActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        cadastrarFrameMenu.setVisible(false);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void txtplataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplataformaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplataformaActionPerformed

    private void txtIdDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDeletarActionPerformed

    private void deletarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBtnActionPerformed
        // TODO add your handling code here:
        model.Games g = new model.Games();
        model.dao.GamesDAO gdao = new model.dao.GamesDAO();
        g.setId(Integer.parseInt(txtIdDeletar.getText()));
        try{
            gdao.deletar(g);
            deletadolbl.setText("Deletado com sucesso!");
        }catch(SQLException | ClassNotFoundException ex){
            deletadolbl.setText("Erro" + ex.getMessage());
        }
        txtIdDeletar.setText("");
        
    }//GEN-LAST:event_deletarBtnActionPerformed

    private void cancelarDltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarDltActionPerformed
        // TODO add your handling code here:
        DeletarFrameMenu.setVisible(false);
        txtIdDeletar.setText("");
        deletadolbl.setText("");
    }//GEN-LAST:event_cancelarDltActionPerformed

    private void AtualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarBtnActionPerformed
        // TODO add your handling code here:
        model.Games g = new model.Games();
        model.dao.GamesDAO gdao = new model.dao.GamesDAO();
        Control.GameControle gControlado = new Control.GameControle();
        g.setPlataforma(txtplataformaupdate.getText() );
        g.setPreco(Double.parseDouble(txtprecoupdate.getText()));
        g.setNotametacritic(Double.parseDouble(txtnotaupdate.getText()));
        g.setId(Integer.parseInt(txtidupdate.getText()));
        boolean sucesso;
        gControlado.ControleConexao();
        try{
            gdao.atualizar(g);
            lblAtualizado.setText("atualizado com Sucesso!");
        }catch(SQLException | ClassNotFoundException ex){
            lblAtualizado.setText("Erro" + ex.getMessage());
        }
        txtplataformaupdate.setText("");
        txtprecoupdate.setText("");
        txtnotaupdate.setText("");
        txtidupdate.setText("");  
    }//GEN-LAST:event_AtualizarBtnActionPerformed

    private void menuItemAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAtualizarActionPerformed
        // TODO add your handling code here:
        FrameAtualizar.setVisible(true);
    }//GEN-LAST:event_menuItemAtualizarActionPerformed

    private void cancelarUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarUpdateBtnActionPerformed
        // TODO add your handling code here:
        FrameAtualizar.setVisible(false);
    }//GEN-LAST:event_cancelarUpdateBtnActionPerformed

    private void ConsultarIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarIdButtonActionPerformed
        // TODO add your handling code here:
        model.Games g = new model.Games();
        model.dao.GamesDAO gdao = new model.dao.GamesDAO();
        g.setId(Integer.parseInt(txtidConsultarId.getText()));
        try{
            gdao.consultarById(g);
            if(g.getNome() != null){
            
            DefaultListModel modelolista = new DefaultListModel();
            modelolista.addElement("Id: " + g.getId());
            modelolista.addElement("Nome: "+g.getNome());
            modelolista.addElement("Sinopse: "+g.getSinopse());
            modelolista.addElement("Lançamento: " + g.getDatalancamento());
            modelolista.addElement("Preço"+ g.getPreco()); 
            modelolista.addElement("Plataforma: " + g.getPlataforma());
            modelolista.addElement("Vendas: " + g.getQuantidadesvendidas());
            modelolista.addElement("Categoria: " + g.getCategoria());
            modelolista.addElement("Desenvolvedora: " + g.getDesenvolvedora());
            modelolista.addElement("Nota MetaCritic: " + g.getNotametacritic());
            consultarList.setModel(modelolista);
            }else{
                LabelErro.setText("Id não encontrado");
                txtidConsultarId.setText("");
            }        
        }catch(SQLException | ClassNotFoundException ex){
            System.out.println("Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_ConsultarIdButtonActionPerformed

    private void txtidConsultarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidConsultarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidConsultarIdActionPerformed

    private void cancelarConsultarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarConsultarIdActionPerformed
        // TODO add your handling code here:
        ConsultarFrame.setVisible(false);
        DefaultListModel modelolista = new DefaultListModel();
        consultarList.setModel(modelolista);
        modelolista.clear();
        txtidConsultarId.setText("");
        
    }//GEN-LAST:event_cancelarConsultarIdActionPerformed

    private void ConsultarTdsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarTdsBtnActionPerformed
        // TODO add your handling code here:
        model.Games g = new model.Games();
        model.dao.GamesDAO gdao = new model.dao.GamesDAO();
        DefaultListModel modelolista = new DefaultListModel();
        
        try{
            gdao.consultarTodos();
            List<model.Games>lgames = gdao.consultarTodos();
            for(model.Games g2 : lgames){
            modelolista.addElement("Id: "+g2.getId());
            modelolista.addElement("Nome: "+g2.getNome());
            modelolista.addElement("Sinopse: "+g2.getSinopse());
            modelolista.addElement("Data de lançamento: "+g2.getDatalancamento());
            modelolista.addElement("Preço: "+ g2.getPreco()); 
            modelolista.addElement("Plataformas: " + g2.getPlataforma());
            modelolista.addElement("Vendidos: "+g2.getQuantidadesvendidas());
            modelolista.addElement("Categoria" + g2.getCategoria());
            modelolista.addElement("Desenvolvedora: "+g2.getDesenvolvedora());
            modelolista.addElement("Nota: "+g2.getNotametacritic());
            modelolista.addElement("***************************");      
            ConsultarTodos.setModel(modelolista);
            }
        }catch(SQLException | ClassNotFoundException ex){
            System.out.println("Erro" + ex.getMessage());
        }
    }//GEN-LAST:event_ConsultarTdsBtnActionPerformed

    private void MenuTdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTdsActionPerformed
        // TODO add your handling code here:
        ConsultarTodosFrame.setVisible(true);
    }//GEN-LAST:event_MenuTdsActionPerformed

    private void CancelarTdsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarTdsBtnActionPerformed
        // TODO add your handling code here:
        ConsultarTodosFrame.setVisible(false);
        DefaultListModel modelolista = new DefaultListModel();
        ConsultarTodos.setModel(modelolista);
        modelolista.clear();
        
    }//GEN-LAST:event_CancelarTdsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarBtn;
    private javax.swing.JButton CancelarTdsBtn;
    private javax.swing.JInternalFrame ConsultarFrame;
    private javax.swing.JButton ConsultarIdButton;
    private javax.swing.JButton ConsultarTdsBtn;
    private javax.swing.JList<String> ConsultarTodos;
    private javax.swing.JInternalFrame ConsultarTodosFrame;
    private javax.swing.JInternalFrame DeletarFrameMenu;
    private javax.swing.JInternalFrame FrameAtualizar;
    private javax.swing.JLabel LabelErro;
    private javax.swing.JMenuItem MenuTds;
    private javax.swing.JMenu arquivoMenu;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JInternalFrame cadastrarFrameMenu;
    private javax.swing.JMenuItem cadastrarMenuItem;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton cancelarConsultarId;
    private javax.swing.JButton cancelarDlt;
    private javax.swing.JButton cancelarUpdateBtn;
    private javax.swing.JList<String> consultarList;
    private javax.swing.JLabel deletadolbl;
    private javax.swing.JButton deletarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAtualizado;
    private javax.swing.JMenuItem menuById;
    private javax.swing.JMenuItem menuItemAtualizar;
    private javax.swing.JMenuItem menuItemDeletar;
    private javax.swing.JLabel platLabel;
    private javax.swing.JLabel platLabel1;
    private javax.swing.JMenu sobreMenu;
    private javax.swing.JLabel sucessoLbl;
    private javax.swing.JTextField txtIdDeletar;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtdev;
    private javax.swing.JTextField txtidConsultarId;
    private javax.swing.JTextField txtidupdate;
    private javax.swing.JTextField txtlancamento;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnota;
    private javax.swing.JTextField txtnotaupdate;
    private javax.swing.JTextField txtplataforma;
    private javax.swing.JTextField txtplataformaupdate;
    private javax.swing.JTextField txtpreco;
    private javax.swing.JTextField txtprecoupdate;
    private javax.swing.JTextField txtsinopse;
    private javax.swing.JTextField txtvenda;
    // End of variables declaration//GEN-END:variables
}
